name: Simple CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test app compilation
        run: |
          echo "Testing application compilation..."
          python -c "import src.app; print('✅ App compiles successfully')"
          python -c "import fastapi; print('✅ FastAPI available')"
          python -c "import uvicorn; print('✅ Uvicorn available')"

      - name: Check for hardcoded secrets
        run: |
          echo "Checking for hardcoded secrets..."
          if grep -r "password=" src/; then
            echo "❌ Hardcoded passwords found!"
            exit 1
          fi
          if grep -r "secret=" src/; then
            echo "❌ Hardcoded secrets found!"
            exit 1
          fi
          if grep -r "api_key" src/; then
            echo "❌ Hardcoded API keys found!"
            exit 1
          fi
          if grep -r "token=" src/; then
            echo "❌ Hardcoded tokens found!"
            exit 1
          fi
          echo "✅ No hardcoded secrets found"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/agrarian-application-repository/temperature-collector-app:latest
            ghcr.io/agrarian-application-repository/temperature-collector-app:sha-${{ github.sha }}

      - name: Test Docker image
        run: |
          echo "Testing Docker image..."
          docker pull ghcr.io/agrarian-application-repository/temperature-collector-app:latest
          docker run -d --name test-app -p 8080:80 ghcr.io/agrarian-application-repository/temperature-collector-app:latest
          sleep 10
          curl -f http://localhost:8080/health || echo "⚠️ Health check failed"
          curl -f http://localhost:8080/ || echo "⚠️ Main endpoint failed"
          docker stop test-app
          docker rm test-app
          echo "✅ Docker image test completed"
